### PR TITLE
Do not enable deploy now column by default.

### PR DESCRIPTION
**Pull request by christ66**
@reviewbybees

### CODE REVIEW

**Comment by aheritier** [comment]
why ?

**Comment by christ66** [comment]
@aheritier Setting the "show by default" option changes the default view for every folder created. If I create 20 new folders each will have the deploy now column even if the folder doesn't use it. It just adds more to the default view as well which can not be modified, so you're `All` view will have this column until a new view is created.

I think it would be better to disable it by default and you select which views and which folders get the view.

**Comment by jglick** [comment]
Perhaps we should change the default value of `shownByDefault` in core. Technically incompatible but arguably for the best.

**Comment by aheritier** [comment]
🐝

**Pull request merged**
