### PR TITLE
Related to [JENKINS-28894] - Broken icons

### PR DESCRIPTION
**Pull request by recena**

### CODE REVIEW

**Comment by recena** [comment]
@stephenc Could you review this PR?

**Comment by stephenc** [comment]
:+1:

**Comment by amuniz** [comment]
:+1:

**Comment by recena** [comment]
@daniel-beck Could you review this PR?

**Comment by daniel-beck** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
:+1:

**Pull request merged**
